extends: default

ignore:
  - node_modules/
  - pnpm-lock.yaml

rules:
  truthy:
    check-keys: false
  line-length:
    max: 120
  comments-indentation: disable
  document-start: disable
  quoted-strings:
    required: only-when-needed
    quote-type: any
  braces:
    # Taskfile uses Go template {{ .VAR }} syntax which triggers false positives
    max-spaces-inside: -1
