version: '3'

vars:
  TS_PACKAGES: sdk executor-node

tasks:
  # ====================
  # Top-level (CI-facing)
  # ====================

  build:
    desc: Build all packages (Go + TS)
    # Note: ts:build is transitive via go:build → executor:bundle → ts:build
    deps: [go:build]

  lint:
    desc: Lint all packages (Go + TS)
    deps: [go:lint, ts:lint]

  test:
    desc: Run all tests (Go + TS)
    deps: [go:test, ts:test]

  test:race:
    desc: Run all tests with race detector
    deps: [go:test:race, ts:test]

  examples:
    desc: Run and validate all examples
    # Note: ts:build is transitive via go:build → executor:bundle → ts:build
    deps: [go:build]
    cmds:
      - pnpm exec tsx scripts/run-examples.ts

  examples:check:
    desc: Validate example files exist (fast check)
    cmds:
      - test -f examples/demo.ts
      - test -f examples/static-html-list/script.ts
      - test -f examples/toy-pagination/script.ts
      - test -f examples/artifact-snapshot/script.ts
      - test -f examples/intentional-failure/script.ts
      - test -f examples/manifest.json

  typecheck:
    desc: Typecheck implementation (TS)
    deps: [ts:typecheck]

  types:
    desc: Typecheck public API contracts (TS)
    deps: [ts:types]

  format:
    desc: Format all packages (Go + TS)
    aliases: [fmt]
    deps: [go:format, ts:format]

  version:lockstep:
    desc: Verify version lockstep (Go == SDK)
    cmds:
      - |
        GO_VERSION=$(grep -oP 'const Version = "\K[^"]+' quarry/types/version.go)
        SDK_VERSION=$(jq -r '.version' sdk/package.json)
        echo "Go version:  $GO_VERSION"
        echo "SDK version: $SDK_VERSION"
        if [ "$GO_VERSION" != "$SDK_VERSION" ]; then
          echo "❌ Version mismatch!"
          exit 1
        fi
        echo "✅ Versions match"

  # ==========
  # Go tasks
  # ==========

  go:build:
    desc: Build Go module
    aliases: [go:b]
    deps: [executor:bundle]
    dir: quarry
    cmds:
      - go build -o quarry ./cmd/quarry

  executor:bundle:
    desc: Bundle executor for embedding
    deps: [ts:build]
    cmds:
      - pnpm -C executor-node run bundle

  go:lint:
    desc: Lint Go module
    aliases: [go:l]
    dir: quarry
    cmds:
      - golangci-lint run ./...

  go:test:
    desc: Test Go module
    aliases: [go:t]
    dir: quarry
    cmds:
      - go test ./...

  cli:parity:
    desc: Validate CLI/config parity artifact
    dir: quarry
    cmds:
      - go test ./cli/cmd -run Parity -v

  go:test:race:
    desc: Test Go module with race detector
    aliases: [go:tr]
    dir: quarry
    cmds:
      - go test -race ./...

  go:format:
    desc: Format Go module
    aliases: [go:fmt]
    dir: quarry
    cmds:
      - golangci-lint run --fix ./...

  # ==================
  # TypeScript tasks
  # ==================

  ts:build:
    desc: Build all TS packages
    aliases: [ts:b]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run build

  ts:lint:
    desc: Lint all TS packages
    aliases: [ts:l]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run lint

  ts:test:
    desc: Run runtime tests (Vitest) for all TS packages
    aliases: [ts:t]
    deps: [ts:build]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run test

  ts:typecheck:
    desc: Typecheck TS implementation (tsc --noEmit)
    aliases: [ts:tc]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run typecheck

  ts:types:
    desc: Validate public TS API contracts (tsd)
    aliases: [ts:d]
    cmds:
      - pnpm -C sdk run test:types

  ts:format:
    desc: Format all TS packages
    aliases: [ts:fmt]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run format
