version: '3'

vars:
  TS_PACKAGES: sdk executor-node

tasks:
  # ====================
  # Top-level (CI-facing)
  # ====================

  build:
    desc: Build all packages (Go + TS)
    deps: [go:build, ts:build]

  lint:
    desc: Lint all packages (Go + TS)
    deps: [go:lint, ts:lint]

  test:
    desc: Test all packages (Go + TS)
    deps: [go:test, ts:test]

  format:
    desc: Format all packages (Go + TS)
    aliases: [fmt]
    deps: [go:format, ts:format]

  # ==========
  # Go tasks
  # ==========

  go:build:
    desc: Build Go module
    aliases: [go:b]
    dir: quarry
    cmds:
      - go build ./...

  go:lint:
    desc: Lint Go module
    aliases: [go:l]
    dir: quarry
    cmds:
      - golangci-lint run ./...

  go:test:
    desc: Test Go module
    aliases: [go:t]
    dir: quarry
    cmds:
      - go test ./...

  go:format:
    desc: Format Go module
    aliases: [go:fmt]
    dir: quarry
    cmds:
      - golangci-lint run --fix ./...

  # ==================
  # TypeScript tasks
  # ==================

  ts:build:
    desc: Build all TS packages
    aliases: [ts:b]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run build

  ts:lint:
    desc: Lint all TS packages
    aliases: [ts:l]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run lint

  ts:test:
    desc: Test all TS packages
    aliases: [ts:t]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run test

  ts:format:
    desc: Format all TS packages
    aliases: [ts:fmt]
    cmds:
      - for: { var: TS_PACKAGES }
        cmd: pnpm -C {{.ITEM}} run format
  
